name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install python moduels
      run: sudo apt update && sudo apt install -y libeigen3-dev python3-setuptools && pip3 install pybind11 pytest numpy scipy cython
    - name: Compile Bybind
      run: export CPATH=/usr/include/eigen3 && cd examples/python && source build.sh
    - name: Test Bybind
      run: |
        cd examples/python
        python3 -m pytest -s -v test.py
    - name: Run cython
      run: |
        cd examples/cython
        python3 setup.py build_ext --inplace && python3 -m pytest -s -v test.py
