name: Run all demos
run-name: ${{ github.actor }} is running
on: [push]
jobs:
  Run_C_example:
    runs-on: ubuntu-latest
    container: mmontanari/devenv:buildenv-fedora
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cmake -E make_directory build
      - run: cmake -E chdir build cmake -DCMAKE_BUILD_TYPE=Release ..
      - run: cmake --build build
      - run: cmake -E chdir build/examples/c/ ./example_lib_opengjk_ce

  Run_GO_example:
    runs-on: ubuntu-latest
    container: mmontanari/devenv:buildenv-fedora
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.15
      - run: cd examples/go/openGJK && go build && go test -v

  Run_Octave_example:
    runs-on: ubuntu-latest
    container: gnuoctave/octave:7.3.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: pwd
      - run: ls
      - run: version
      - run: cd examples/matlab/; run runme.m
